services:
  dormant:
    image: s1s5/rust-dev:1.97.1-26.04
    command:
      - cargo
      - watch
      - -s
      - 'cargo run --bin dormant'
    environment:
      HOME: "${HOME}"
      CARGO_HOME: "${HOME}/.cargo"
      RUSTUP_HOME: "/home/dev/.rustup"
      RUST_LOG: debug,h2=info,hyper=info,tower=info,bollard=error
      DORMANT_SELF_NETWORK: "${DORMANT_SELF_NETWORK:-}"
      DORMANT_DOCKER_SOCKET: "${DORMANT_DOCKER_SOCKET:-/run/user/1000/docker.sock}"
      DORMANT_LISTEN: "${DORMANT_LISTEN:-0.0.0.0:80}"
      DORMANT_IDLE_CHECK_INTERVAL_SECS: "${DORMANT_IDLE_CHECK_INTERVAL_SECS:-10}"
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - ${HOME}/.cargo/.global-cache:${HOME}/.cargo/.global-cache
      - ${HOME}/.cargo/registry:${HOME}/.cargo/registry
      - ${HOME}/.cargo/git:${HOME}/.cargo/git
      - /run/user/1000/docker.sock:/run/user/1000/docker.sock
    stop_grace_period: 1s
    networks:
      - dormant
      - global
    ports:
      - "${PORT:-18000}:18000"
      - "18101:18101"
      - "18102:18102"
      - "18103:18103"

networks:
  dormant:
    name: dormant
    external: true
  global:
    name: global
    external: true
